// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateItem(req: $models.CreateItemRequest): $CancellablePromise<$models.ItemResponse> {
    return $Call.ByID(3877123207, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(2459545088, id);
}

export function GetItem(id: string): $CancellablePromise<$models.ItemResponse> {
    return $Call.ByID(493253095, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetVaultMeta(): $CancellablePromise<$models.VaultMetaResponse> {
    return $Call.ByID(2104930121).then(($result: any) => {
        return $$createType1($result);
    });
}

export function InitVault(req: $models.InitVaultRequest): $CancellablePromise<$models.VaultMetaResponse> {
    return $Call.ByID(441369266, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IsVaultInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(4254234582);
}

export function ListItems(req: $models.ListItemsRequest): $CancellablePromise<$models.ItemResponse[]> {
    return $Call.ByID(364795720, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(1761881669);
}

export function RecoverVault(req: $models.RecoverVaultRequest): $CancellablePromise<void> {
    return $Call.ByID(2685420012, req);
}

export function UnlockVault(req: $models.UnlockVaultRequest): $CancellablePromise<void> {
    return $Call.ByID(3100085836, req);
}

export function UpdateItem(req: $models.UpdateItemRequest): $CancellablePromise<$models.ItemResponse> {
    return $Call.ByID(2042180846, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ItemResponse.createFrom;
const $$createType1 = $models.VaultMetaResponse.createFrom;
const $$createType2 = $Create.Array($$createType0);
