// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateItemRequest {
    "title": string;
    "username": string;
    "password": string;
    "website": string;
    "notes": string;
    "category": string;
    "favorite": boolean;
    "tags": string[];

    /** Creates a new CreateItemRequest instance. */
    constructor($$source: Partial<CreateItemRequest> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("website" in $$source)) {
            this["website"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateItemRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateItemRequest {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new CreateItemRequest($$parsedSource as Partial<CreateItemRequest>);
    }
}

export class InitVaultRequest {
    "vault_name": string;
    "master_password": string;

    /** Creates a new InitVaultRequest instance. */
    constructor($$source: Partial<InitVaultRequest> = {}) {
        if (!("vault_name" in $$source)) {
            this["vault_name"] = "";
        }
        if (!("master_password" in $$source)) {
            this["master_password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitVaultRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InitVaultRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitVaultRequest($$parsedSource as Partial<InitVaultRequest>);
    }
}

export class ItemResponse {
    "id": string;
    "title": string;
    "username": string;
    "password": string;
    "website": string;
    "notes": string;
    "category": string;
    "favorite": boolean;
    "tags": string[];
    "created_at": string;
    "updated_at": string;

    /** Creates a new ItemResponse instance. */
    constructor($$source: Partial<ItemResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("website" in $$source)) {
            this["website"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemResponse {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new ItemResponse($$parsedSource as Partial<ItemResponse>);
    }
}

export class ListItemsRequest {
    "keyword": string;
    "tag": string;
    "favorite": boolean | null;
    "category": string;

    /** Creates a new ListItemsRequest instance. */
    constructor($$source: Partial<ListItemsRequest> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = null;
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListItemsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListItemsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListItemsRequest($$parsedSource as Partial<ListItemsRequest>);
    }
}

export class UnlockVaultRequest {
    "master_password": string;

    /** Creates a new UnlockVaultRequest instance. */
    constructor($$source: Partial<UnlockVaultRequest> = {}) {
        if (!("master_password" in $$source)) {
            this["master_password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnlockVaultRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UnlockVaultRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnlockVaultRequest($$parsedSource as Partial<UnlockVaultRequest>);
    }
}

export class UpdateItemRequest {
    "id": string;
    "title": string;
    "username": string;
    "password": string;
    "website": string;
    "notes": string;
    "category": string;
    "favorite": boolean;
    "tags": string[];

    /** Creates a new UpdateItemRequest instance. */
    constructor($$source: Partial<UpdateItemRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("website" in $$source)) {
            this["website"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateItemRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateItemRequest {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new UpdateItemRequest($$parsedSource as Partial<UpdateItemRequest>);
    }
}

export class VaultMetaResponse {
    "name": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new VaultMetaResponse instance. */
    constructor($$source: Partial<VaultMetaResponse> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultMetaResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultMetaResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultMetaResponse($$parsedSource as Partial<VaultMetaResponse>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
